learning_templates/basicApp/urls.py
from django.conf.urls import url
from . import views


# Template tagging
app_name = 'basicApp'

urlpatterns=[
	url(r'^relative/$',views.relative,name='relative'),
	url(r'^other/$',views.other,name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basicApp import views

urlpatterns = [
	url(r'^$',views.index,name="index"),
    path('admin/', admin.site.urls),
    url(r'^basicApp/',include('basicApp.urls')),
]

learning_templates/basicApp/models.py
from django.db import models

# Create your models here.

learning_templates/basicApp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	context_dict = {'text':'hello world','number':100}
	return render(request, 'basicApp/index.html',context_dict)

def other(request):
	return render(request, 'basicApp/other.html')

def relative(request):
	return render(request, 'basicApp/relative_url_templates.html')

learning_templates/templates/basicApp/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Base</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			<ul class="nav navbar-nav">
				<li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
				<li><a class="nav-item nav-link" href="{% url 'admin:index' %}">ADMIN</a></li>
				<li><a class="nav-item nav-link" href="{% url 'basicApp:other' %}">OTHER</a></li>
			</ul>
		</div>
	</nav>

	<div class="container">
		{% block body_block %}
<!-- 		Anithing outside this will be inherited if you extend-->
 		{% endblock %}
	</div>


</body>
</html>

learning_templates/templates/basicApp/index.html
<!DOCTYPE html>
{% extends "basicApp/base.html" %}
{% block body_block %}

	<h1>WELCOME TO INDEX</h1>
<!-- 	<h1>This is index.html page showing!</h1>
 -->	
 	<h1>{{ text|cut:'hello' }}</h1>
 	<h1>{{ number|add:"99" }}</h1>
 	
	{% endblock %}

learning_templates/templates/basicApp/other.html
<!DOCTYPE html>
{% extends "basicApp/base.html" %}
{% block body_block %}
	<h1>WELCOME TO OTHER</h1>
	<h2>This is an example of template inheritance</h2>
	{% endblock %}

learning_templates/templates/basicApp/relative_url_templates.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
	<a href="{% url 'basicApp:other' %}">THE OTHER PAGE</a>
	<a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
	<a href="{% url 'index' %}">LINK TO INDEX</a>

</body>
</html>